
. ./config.env

#ssh oracle@${TARGET_HOST} ". /home/oracle/.bash_profile;sqlplus ${TARGET_SCHEMA}/${TARGET_SCHEMA_PASSWORD}@${TARGET_INSTANCE} << EOF
#DROP TABLE cdc;
#EOF"

ssh oracle@${TARGET_HOST} ". /home/oracle/.bash_profile;sqlplus ${TARGET_CDC_SCHEMA_USER}/${TARGET_CDC_SCHEMA_PASSWORD}@${TARGET_INSTANCE} << EOF

--DROP TABLE cdc;

CREATE TABLE cdc
(
  id number null,
  description varchar2(100) null
);

CREATE TABLE cdc2
(
  id number null,
  description varchar2(100) null
);


ALTER TABLE cdc ADD (
   SHAREPLEX_SOURCE_TIME       TIMESTAMP,
   SHAREPLEX_SOURCE_USERID     NUMBER,
   SHAREPLEX_SOURCE_OPERATION  VARCHAR2(20),
   SHAREPLEX_SOURCE_SCN        NUMBER,
   SHAREPLEX_SOURCE_ROWID      ROWID,
   SHAREPLEX_SOURCE_TRANS      VARCHAR2(60),
   SHAREPLEX_OPERATION_SEQ     NUMBER,
   SHAREPLEX_SOURCE_HOST       VARCHAR2(60),
   SHAREPLEX_QUEUENAME         VARCHAR2(60),
   SHAREPLEX_SOURCE_ID         VARCHAR2(60),
   SHAREPLEX_CHANGE_ID         NUMBER,
   SHAREPLEX_TRANS_SIZE        NUMBER);

ALTER TABLE cdc2 ADD (
   SHAREPLEX_SOURCE_TIME       TIMESTAMP,
   SHAREPLEX_SOURCE_USERID     NUMBER,
   SHAREPLEX_SOURCE_OPERATION  VARCHAR2(20),
   SHAREPLEX_SOURCE_SCN        NUMBER,
   SHAREPLEX_SOURCE_ROWID      ROWID,
   SHAREPLEX_SOURCE_TRANS      VARCHAR2(60),
   SHAREPLEX_OPERATION_SEQ     NUMBER,
   SHAREPLEX_SOURCE_HOST       VARCHAR2(60),
   SHAREPLEX_QUEUENAME         VARCHAR2(60),
   SHAREPLEX_SOURCE_ID         VARCHAR2(60),
   SHAREPLEX_CHANGE_ID         NUMBER,
   SHAREPLEX_TRANS_SIZE        NUMBER);

exit

EOF"

